name: premarital_match
description: "Taalof pre-marital compatibility and counseling app."

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.13.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_logo.png
    - assets/fonts/arial.ttf
    - assets/fonts/arialbd.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png


